-- MySQL Script generated by MySQL Workbench
-- Sun Aug 27 08:58:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gym_argente
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gym_argente` ;

-- -----------------------------------------------------
-- Schema gym_argente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym_argente` DEFAULT CHARACTER SET utf8 ;
USE `gym_argente` ;

-- -----------------------------------------------------
-- Table `gym_argente`.`personnes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`personnes` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`personnes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(256) NULL,
  `telephone` CHAR(10) NOT NULL,
  `courriel` VARCHAR(96) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_argente`.`gestionnaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`gestionnaires` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`gestionnaires` (
  `personne` INT NOT NULL,
  `mot_passe` CHAR(97) NOT NULL,
  PRIMARY KEY (`personne`),
  UNIQUE INDEX `personne_UNIQUE` (`personne` ASC) VISIBLE,
  CONSTRAINT `personne_gestionnaire`
    FOREIGN KEY (`personne`)
    REFERENCES `gym_argente`.`personnes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_argente`.`specialites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`specialites` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`specialites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_argente`.`specialistes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`specialistes` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`specialistes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personne` INT NOT NULL,
  `specialite` INT NOT NULL,
  `mot_passe` CHAR(97) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `personne_idx` (`personne` ASC) VISIBLE,
  INDEX `specialite_idx` (`specialite` ASC) VISIBLE,
  CONSTRAINT `personne_specialiste`
    FOREIGN KEY (`personne`)
    REFERENCES `gym_argente`.`personnes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `specialite`
    FOREIGN KEY (`specialite`)
    REFERENCES `gym_argente`.`specialites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_argente`.`plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`plans` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `duree` INT NOT NULL,
  `prix` DECIMAL NOT NULL,
  `acces_appareils` INT NOT NULL DEFAULT 0,
  `acces_cours_groupe` INT NOT NULL DEFAULT 0,
  `prix_cours_groupe` DECIMAL NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_argente`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`clients` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`clients` (
  `personne` INT NOT NULL,
  `adhesion` DATE NOT NULL,
  `renouvellement` DATE NOT NULL,
  `fin_abonnement` DATE NOT NULL,
  `fin_acces_appareils` DATE NOT NULL,
  `heures_specialistes` INT NOT NULL DEFAULT 0,
  `heures_specialistes_utilise` INT NOT NULL DEFAULT 0,
  `cours_groupe_semaine` INT NOT NULL DEFAULT 0,
  `plan` INT NULL,
  PRIMARY KEY (`personne`),
  UNIQUE INDEX `personne_UNIQUE` (`personne` ASC) VISIBLE,
  INDEX `plan_idx` (`plan` ASC) VISIBLE,
  CONSTRAINT `personne_client`
    FOREIGN KEY (`personne`)
    REFERENCES `gym_argente`.`personnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plan`
    FOREIGN KEY (`plan`)
    REFERENCES `gym_argente`.`plans` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_argente`.`rendez_vous`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`rendez_vous` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`rendez_vous` (
  `date_heure` DATETIME NOT NULL,
  `client` INT NOT NULL,
  `specialiste` INT NOT NULL,
  INDEX `client_idx` (`client` ASC) VISIBLE,
  INDEX `specialiste_idx` (`specialiste` ASC) VISIBLE,
  CONSTRAINT `client`
    FOREIGN KEY (`client`)
    REFERENCES `gym_argente`.`clients` (`personne`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `specialiste`
    FOREIGN KEY (`specialiste`)
    REFERENCES `gym_argente`.`specialistes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_argente`.`types_notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`types_notifications` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`types_notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_argente`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gym_argente`.`notifications` ;

CREATE TABLE IF NOT EXISTS `gym_argente`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_heure` DATETIME NOT NULL,
  `type` INT NOT NULL,
  `client` INT NOT NULL,
  `vu` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `type_idx` (`type` ASC) VISIBLE,
  INDEX `client_idx` (`client` ASC) VISIBLE,
  CONSTRAINT `type`
    FOREIGN KEY (`type`)
    REFERENCES `gym_argente`.`types_notifications` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `client_notification`
    FOREIGN KEY (`client`)
    REFERENCES `gym_argente`.`clients` (`personne`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
